name: MobileAppBuild
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Set Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: npm install
      - run: npx cap add android
      - run: npx cap sync
      - run: cd android && ./gradlew assembleDebug
      - uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: android/app/build/outputs/apk/debug/app-debug.apk
